Config = {}

Config.Locale = 'tr'

Config.TarotCards = {
    [1] = {name = 'asalarin-altilisi', description = 'Asaların Altılısı'},
    [2] = {name = 'asalarin-asi', description = 'Asaların Ası'},
    [3] = {name = 'asalarin-beslisi', description = 'Asaların Beşlisi'},
    [4] = {name = 'asalarin-dokuzlusu', description = 'Asaların Dokuzlusu'},
    [5] = {name = 'asalarin-dortlusu', description = 'Asaların Dörtlüsü'},
    [6] = {name = 'asalarin-ikilisi', description = 'Asaların İkilisi'},
    [7] = {name = 'asalarin-krali', description = 'Asaların Kralı'},
    [8] = {name = 'asalarin-kralicesi', description = 'Asaların Kraliçesi'},
    [9] = {name = 'asalarin-onlusu', description = 'Asaların Onlusu'},
    [10] = {name = 'asalarin-sekizlisi', description = 'Asaların Sekizlisi'},
    [11] = {name = 'asalarin-sovalyesi', description = 'Asaların Şövalyesi'},
    [12] = {name = 'asalarin-uclusu', description = 'Asaların Üçlüsü'},
    [13] = {name = 'asalarin-prensi', description = 'Asaların Prensi'},
    [14] = {name = 'asalarin-yedilisi', description = 'Asaların Yedilisi'},
    [15] = {name = 'kiliclarin-altilisi', description = 'Kılıçların Altılısı'},
    [16] = {name = 'kiliclarin-asi', description = 'Kılıçların Ası'},
    [17] = {name = 'kiliclarin-beslisi', description = 'Kılıçların Beşlisi'},
    [18] = {name = 'kiliclarin-dokuzlusu', description = 'Kılıçların Dokuzlusu'},
    [19] = {name = 'kiliclarin-dortlusu', description = 'Kılıçların Dörtlüsü'},
    [20] = {name = 'kiliclarin-ikilisi', description = 'Kılıçların İkilisi'},
    [21] = {name = 'kiliclarin-krali', description = 'Kılıçların Kralı'},
    [22] = {name = 'kiliclarin-kralicesi', description = 'Kılıçların Kraliçesi'},
    [23] = {name = 'kiliclarin-onlusu', description = 'Kılıçların Onlusu'},
    [24] = {name = 'kiliclarin-sekizlisi', description = 'Kılıçların Sekizlisi'},
    [25] = {name = 'kiliclarin-sovalyesi', description = 'Kılıçların Şövalyesi'},
    [26] = {name = 'kiliclarin-uclusu', description = 'Kılıçların Üçlüsü'},
    [27] = {name = 'kiliclarin-prensi', description = 'Kılıçların Prensi'},
    [28] = {name = 'kiliclarin-yedilisi', description = 'Kılıçların Yedilisi'},
    [29] = {name = 'kupalarin-altilisi', description = 'Kupaların Altılısı'},
    [30] = {name = 'kupalarin-asi', description = 'Kupaların Ası'},
    [31] = {name = 'kupalarin-beslisi', description = 'Kupaların Beşlisi'},
    [32] = {name = 'kupalarin-dokuzlusu', description = 'Kupaların Dokuzlusu'},
    [33] = {name = 'kupalarin-dortlusu', description = 'Kupaların Dörtlüsü'},
    [34] = {name = 'kupalarin-ikilisi', description = 'Kupaların İkilisi'},
    [35] = {name = 'kupalarin-krali', description = 'Kupaların Kralı'},
    [36] = {name = 'kupalarin-kralicesi', description = 'Kupaların Kraliçesi'},
    [37] = {name = 'kupalarin-onlusu', description = 'Kupaların Onlusu'},
    [38] = {name = 'kupalarin-sekizlisi', description = 'Kupaların Sekizlisi'},
    [39] = {name = 'kupalarin-sovalyesi', description = 'Kupaların Şövalyesi'},
    [40] = {name = 'kupalarin-uclusu', description = 'Kupaların Üçlüsü'},
    [41] = {name = 'kupalarin-prensi', description = 'Kupaların Prensi'},
    [42] = {name = 'kupalarin-yedilisi', description = 'Kupaların Yedilisi'},
    [43] = {name = 'mahkeme-uyanisi', description = 'Mahkeme Uyanışı'},
    [44] = {name = 'sir-adalet', description = 'Sir Adalet'},
    [45] = {name = 'sir-asiklar', description = 'Sir Aşıklar'},
    [46] = {name = 'sir-asilmis-adam', description = 'Sir Asılmış Adam'},
    [47] = {name = 'sir-ay', description = 'Sir Ay'},
    [48] = {name = 'sir-basrahibe-azize', description = 'Sir Başrahibe Azize'},
    [49] = {name = 'sir-basrahip', description = 'Sir Başrahip'},
    [50] = {name = 'sir-buyucu', description = 'Sir Büyücü'},
    [51] = {name = 'sir-deli', description = 'Sir Deli'},
    [52] = {name = 'sir-denge', description = 'Sir Denge'},
    [53] = {name = 'sir-dunya', description = 'Sir Dünya'},
    [54] = {name = 'sir-gunes', description = 'Sir Güneş'},
    [55] = {name = 'sir-imparator', description = 'Sir İmparator'},
    [56] = {name = 'sir-imparatorice', description = 'Sir İmparatoriçe'},
    [57] = {name = 'sir-kader-carki', description = 'Sir Kader Çarkı'},
    [58] = {name = 'sir-kuvvet', description = 'Sir Kuvvet'},
    [59] = {name = 'sir-munvezi', description = 'Sir Mümeyyiz'},
    [60] = {name = 'sir-olum', description = 'Sir Ölüm'},
    [61] = {name = 'sir-savas-arabasi', description = 'Sir Savaş Arabası'},
    [62] = {name = 'sir-seytan', description = 'Sir Şeytan'},
    [63] = {name = 'sir-yikilan-kule', description = 'Sir Yıkılan Kule'},
    [64] = {name = 'sir-yildiz', description = 'Sir Yıldız'},
    [65] = {name = 'tilsimlarin-altilisi', description = 'Tılsımların Altılısı'},
    [66] = {name = 'tilsimlarin-asi', description = 'Tılsımların Ası'},
    [67] = {name = 'tilsimlarin-beslisi', description = 'Tılsımların Beşlisi'},
    [68] = {name = 'tilsimlarin-dokuzlusu', description = 'Tılsımların Dokuzlusu'},
    [69] = {name = 'tilsimlarin-dortlusu', description = 'Tılsımların Dörtlüsü'},
    [70] = {name = 'tilsimlarin-ikilisi', description = 'Tılsımların İkilisi'},
    [71] = {name = 'tilsimlarin-krali', description = 'Tılsımların Kralı'},
    [72] = {name = 'tilsimlarin-kralicesi', description = 'Tılsımların Kraliçesi'},
    [73] = {name = 'tilsimlarin-onlusu', description = 'Tılsımların Onlusu'},
    [74] = {name = 'tilsimlarin-sekizlisi', description = 'Tılsımların Sekizlisi'},
    [75] = {name = 'tilsimlarin-sovalyesi', description = 'Tılsımların Şövalyesi'},
    [76] = {name = 'tilsimlarin-uclusu', description = 'Tılsımların Üçlüsü'},
    [77] = {name = 'tilsimlarin-prensi', description = 'Tılsımların Prensi'},
    [78] = {name = 'tilsimlarin-yedilisi', description = 'Tılsımların Yedilisi'}    
}

Config.Texts = {
    ['en'] = {
        ['tarot_drawn'] = 'Card: ',
        ['tarot_description'] = 'Kart ismi: ',
    },
    ['tr'] = {
        ['tarot_drawn'] = 'Kart: ',
        ['tarot_description'] = 'Kart ismi: ',
    },
}